// Dependency-free and shared by Node and Cloudflare. This is a cheap relevance
// screen, not a semantic classifier; the model still checks actual user intent.
const topic = /\b(premiere|astra|aeterna|penabur|pskg|events?|acara\w*|kegiatan|competition\w*|registration|register\w*|sign\s?up|join|participat\w*|sponsor\w*|proposal\w*|partnership|partner|collaborat\w*|volunteer\w*|invite|invitation|e-invite|ticket\w*|closing|opening|preopening|pre-opening|merch\w*|venue|schedule\w*|dates?|deadline|committee|contact\w*|whatsapp|gavynn|grace|instagram\w*|futsal|basketball|volleyball|badminton|mural|vocal|band|dance|speedcubing|swimming|debate|speech|lomba\w*|kompetisi|pendaftaran|daftar\w*|undangan|tiket|penutupan|pembukaan|jadwal|tanggal|panitia|alamat|kontak|renang\w*|pidato|debat|voli|basket|tangkis|vokal|tari|rubik|rulebook\w*|rules?|peraturan|aturan|syarat\w*|persyaratan\w*|requirement\w*|eligib\w*|grades?|kelas|smp|sma|sd|school\w*|sekolah\w*|students?|murid|pelajar|alumni|team\w*|tim|coach|pelatih|players?|pemain|boys?|girls?|putra|putri|prizes?|hadiah\w*|troph\w*|piala|certificat\w*|sertifikat|brackets?|bagan|match\w*|pertandingan|equipment|alat|uniform\w*|seragam\w*|dress code|baju|theme|tema|nyanyi|sing|cubes?|distances?|scoring|penilaian\w*|winners?|pemenang|results?|hasil|technical meeting|performing|performers?|guest stars?|bintang tamu\w*|artists?|artis\w*|concert|konser|spectator\w*|penonton|parents?|orang tua|friends?|teman|early bird|vip|doors|pintu|booth|logo|donation\w*|donasi|umkm|relawan|kolaborasi|kerja sama|slot|pdf|link\w*|form\w*|dokumen|documents?|fees?|biaya\w*|cost\w*|price\w*|harga\w*|free|gratis|pay\w*|bayar\w*|qris|bank transfer|transfer bank|refund|cancell?\w*|batal\w*|confirmation|konfirmasi|data|details|shirt\w*|kaos|sizes?|ukuran|orders?|pesanan|catalogue|catalog|katalog|deliver\w*|dikirim|diambil|address|location|lokasi\w*|tempat\w*|map|peta|parking|parkir|drop off|transport\w*|makanan|minuman|food|drinks?|toilets?|toilet\w*|wheelchair|kursi roda|first aid|p3k|security|keamanan|bring|bawa|rain|hujan|indoor\w*|outdoor\w*|february|februari)\b/i;
const injection = /ignore.{0,35}(instruction|previous|system)|system\s*prompt|api\s*key|jailbreak|developer\s*message|abaikan.{0,30}(instruksi|perintah)|\x60{3}|<script|\b(write|generate|debug)\b.{0,25}\b(code|python|javascript|essay)\b/i;
// Explicit unrelated requests take precedence, even after a greeting or event
// keyword. Avoid broad words such as "food" and "band" that fit event questions.
const unrelated = /\b(jokes?|lelucon|python|javascript|algebra|equation|matematika|capital of|ibu kota|president|presiden|recipes?|resep|bake|bikin kue|weather in|cuaca di|gaming laptop|laptop gaming|phone should i buy|hp apa|bitcoin|stocks?|saham|headache|sakit kepala|medicine should i take|obat apa|romantic poem|puisi romantis|history essay|pr sejarah|japanese song|lagu jepang|netflix|harry potter|puppy|cat not eating|anjing|kucing\w*|holiday in|liburan|flights?|penerbangan|hotels?|electric cars|mobil listrik|pizza restaurant|restoran pizza|lose weight|menurunkan berat|workout routine|rutinitas olahraga|quantum|kuantum|black holes?|lubang hitam|planets?|planet|astrology|astrologi|horoscope|zodiak\w*|passport|paspor|income tax|pajak penghasilan|legal advice|saran hukum|divorce|perceraian|washing machine|mesin cuci|wifi slow|wifi rumah|grow tomatoes|menanam tomat|nba|fifa|piala dunia|teach me how to shoot|ajari teknik|favorite band|band favorit|wedding speech|pidato pernikahan|adobe premiere|film premiere|premiere film|amazon|roleplay|pura pura jadi)\b/i;
const genericWords = new Set(`hi hello hey heyy halo hai permisi kak good morning afternoon evening there are you can could would will please pls plz help me i im i'm new here need some info information give a an the quick overview explain this that these those it its it's whats what's what wheres when where who how why is isn't are arent was does do did don't do not about for to of at in on by from and or with without more much many long again tell ask something anything know basics start happening going guys purpose run only official website site work works should mean means thank thanks okay ok got yes no sure english en id indonesian bahasa indonesia inggris use answer reply shorter briefly short more details clarify understand don't does doesn't starts ends time year duration contact want like interested ini itu apaan apa sih ya yah dong deh nih aku saya kamu kalian kami kita baru buka buat untuk sama kepada oleh siapa penyelenggaranya ngadain diurus artinya jelasin jelaskan dijelasin acaranya bantu tolong ada orang pagi siang sore malam selamat kasih ringkasan boleh minta informasi informasinya cuma anak luar resmi kan gimana gmn bagaimana cara caranya kerjanya mulainya dari mana dimana ke di kesananya disana ngapain tujuan cerita sedikit singkat aja penasaran belum paham detailnya makasih terima kasih oke iya nggak gak ga tidak dulu mau tanya bisa gabisa kenapa kapan mulai selesainya selesai jam berapa lengkap lebih jawab pakai pake kalau kalo cewek cowok udah sudah lagi maksudnya lanjut tentang tahun bulan besok nanti hari dapat dapet perlu harus apakah bayar biaya tempat lokasi teman boleh ikut ikutan masuk dateng datang bantuannya bantuin penjelasan sorry maaf actually also then so too both still really sekarang berapaan harganya biayanya`.split(/\s+/));
const controls = /[\u0000-\u0008\u000b\u000c\u000e-\u001f]/;
const visitorIntent = /\b(organiz\w*|hosts?|activities|sports?|age|ages|waiting list|contests?|company|business|dropped off|rains?|usia|umur\w*|terdaftar|olahraga|perusahaan|tampil|dihubungi)\b/i;
for (const word of 'u ur get web tau yang lebih dari satu terus if be yo wats which one pick picked choose chose was my last called mention mentioned remember repeat your a lot thx thnx terimakasih ringkas masih gk kok gitu adults available interested'.split(' ')) genericWords.add(word);

export function filterQuestion(input, hasContext = false) {
  if (typeof input !== 'string') return { ok: false, code: 'invalid' };
  if (controls.test(input)) return { ok: false, code: 'invalid' };
  const message = input.normalize('NFKC').replace(/[’‘]/g, "'").trim().replace(/\s+/g, ' ');
  if (message.length < 2 || message.length > 400) return { ok: false, code: 'invalid' };
  if (/(.)\1{7,}/iu.test(message) || /https?:\/\/|www\./i.test(message) || injection.test(message) || unrelated.test(message)) return { ok: false, code: 'scope' };
  const words = message.toLowerCase().match(/[\p{L}]+(?:'[\p{L}]+)?/gu) || [];
  if (!words.length || words.some(word => word.length > 35) || (words.length > 10 && new Set(words).size / words.length < .3)) return { ok: false, code: 'scope' };
  // Missing punctuation and terse follow-ups are fine. A greeting or pronoun
  // alone must not whitelist an otherwise arbitrary unrelated request.
  const conversational = words.length <= 24 && words.every(word => genericWords.has(word));
  if (!topic.test(message) && !visitorIntent.test(message) && !conversational) return { ok: false, code: 'scope' };
  return { ok: true, message };
}
